theodi/comma-chameleon

hot.js

Would be added anyway if the difference between number of columns in
table and in array was 0. Included conditional for 0 value.

Handle table display csvs

---

bower.json
main.js
package.json
select_worksheet.html

Import Excel files

---

bower.json
datapackage.html
datapackage.js
hot.js
main.js
package.json

Export as Datapackage

---

bower.json
hot.js
index.html
panels.css

Now displays validation messages in the right pane. Type of error/warning is provided (along with row and column if they are available), but these are not descriptive enough, they are the symbols in the [csvlint.rb readme](https://github.com/theodi/csvlint.rb/blob/master/README.md#errors)

Display validation messages

---

hot.js
index.html

Also bug fix with checking whether a cell is undefined.

Add cells to fill table (ragged rows)

---

hot.js

So, it turns out that jQuery-csv can generate a csv string from an array, so we'll use that

Handle quotes in cells

---

hot.js

Should only correct undefined cells not null.

Bug fix on ragged rows correction

---

README.md
app/comma-chameleon/hot.js
app/comma-chameleon/index.js
app/main.js
package.json

Should fix #45 
@pikesley Could you do me a favour and pull down the repo and follow the instructions and check this works? It works fine for me, but I think I tried to implement this before and it broke for other people :/

Fix rendering issues

---

app/comma-chameleon/validate.js
app/test/renderer/validate_spec.js

Fixes #80 
I ❤️  the fact we have tests now

Refer to columns by letter

---

app/comma-chameleon/file-actions.js
app/comma-chameleon/index.js
app/test/renderer/file_actions_spec.js

Drag and drop file

---

.gitignore
app/bower.json
app/comma-chameleon/css/datapackage.css
app/comma-chameleon/views/datapackage.html

Datapackage tweaks

---

main/github.js
package.json
test/main/github_spec.js
views/views-content/choose-repo.html
views/views-content/github.html

Update to support new Octopub API

---

main/menu.js

enabled 'Save' menu item

---

renderer/index.js

make use of abstraction for save() defined in file-actions.js

---

main/datapackage.js
main/file.js
main/github.js
main/menu.js
main/utils.js
renderer/file-actions.js
renderer/index.js
test/main/datapackage_spec.js
test/renderer/file_actions_spec.js

Based on the comments in issue #117 I've made a start on this.
There are several places where work needs to be done in order to fully support other separator characters:
I'll tick them off as I get them done. Once I'm happy for final review/merge I will remove the WIP tag, but feel free to provide review or comments on what I've done so far as I'm working on it.

Support other separators

---

renderer/menu.js

add ability to remove a range of rows or columns

---

renderer/index.js
renderer/menu.js

* Fix issue #69
* Fix issue #116
* Behave predictably if inserting rows/cols when a range of cells is selected

Improvements to insert row/insert col behaviour

---

gulpfile.js
scripts/build.js

Build with correct CsvLint binary on linux-x64

---

renderer/hot.js
renderer/index.js
renderer/loader.js
renderer/validate.js
test/renderer/file_actions_spec.js

Add loading indicator

---

main.js
main/file.js

Does the job under Linux and Windows - could do with a test on MacOS
Closes #75

Accept filename as positional argument to enable 'open with..' functionality

---

README.md

I spent more time trying to find a link to a website in the README than I have making this PR.
This is unfortunate.

There is a website. It is not a secret.

---

.jshintignore
.jshintrc
.travis.yml
gulpfile.js
main.js
main/file.js
main/github.js
main/menu.js
main/schema.js
main/tools.js
main/validate.js
package.json
renderer/.jshintrc
renderer/file-actions.js
renderer/hot.js
renderer/ragged-rows.js
renderer/schemawizard.js
renderer/validate.js
scripts/build.js
test/main/datapackage_spec.js
test/main/github_spec.js
test/main/schema_spec.js
test/main/test.js
test/main/validate_spec.js
test/renderer/ragged-rows_spec.js
test/renderer/test.js
test/renderer/validate_spec.js

While working on this project, I have spotted a few problems which were tricky to track down but caused by small issues such as missing var statements. e.g: PRs #123 and #140
This kind of error should be trivial to spot early by checking code with a linter before committing. As such, I have:
* Added [JSHint](http://jshint.com/) as a dev dependency
* Checked the codebase against it
* Fixed all the warnings (I've tried to split the commits up so the actual meaningful changes aren't just buried with adding piles of semicolons - hopefully this makes review a bit easier)
* Set up (what I consider to be) a reasonable configuration
* Added `jshint` to the travis build config
This should prevent more of these errors from creeping in during future development and make code review less onerous. …

Run jshint in travis build

---

README.md

areas where corrections amendments required now in #146

Alignment w/ toolbox readme template for consistency

---

scripts/build.js

Fix Application Name

---

scripts/build.js

remove use of deprecated version param
